[package]
name = "app"
version = "0.1.0"
authors = ["Nate Strandberg"]
default-run = "app"
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.8", features = [] }

[dependencies]
anyhow = "1.0.57"
serde_json = "^1.0"
serde_yaml = "^0.8.24"
reqwest = { version = "^0.11", features = ["json"] }
tokio = { version = "^1", features = ["full"] }
serde = { version = "^1.0", features = ["derive"] }
tauri = { version = "1.0.0-rc.9", features = ["api-all", "system-tray"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem - DO NOT remove this!
custom-protocol = [ "tauri/custom-protocol" ]
